// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyu4eHBzP5jzapv81D8P9kbkJ1QZyaVpA',
    appId: '1:863335713047:web:2456bf256913275eeecf52',
    messagingSenderId: '863335713047',
    projectId: 'cinematch-a5f16',
    authDomain: 'cinematch-a5f16.firebaseapp.com',
    storageBucket: 'cinematch-a5f16.appspot.com',
    measurementId: 'G-2H9PEEH2RN',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhEgmXU7Q1D9JFrQN2gdVxZTcK0xQmmnE',
    appId: '1:863335713047:ios:a55152514dde5eb7eecf52',
    messagingSenderId: '863335713047',
    projectId: 'cinematch-a5f16',
    storageBucket: 'cinematch-a5f16.appspot.com',
    iosClientId: '863335713047-j0rnnkqfbbicqo4g89jqqok8rqhei71m.apps.googleusercontent.com',
    iosBundleId: 'com.Ballygorey.vthacks2022',
  );
}
